### PR TITLE
add support for refactor command

### PR DESCRIPTION
**Pull request by ananthakumaran**
introduced by https://github.com/Microsoft/TypeScript/pull/15569

### CODE REVIEW

**Comment by josteink** [comment]
Looks good upon initial skimming, but I'm on vacation the next 3 weeks and won't be able to properly review this until after that. 

Hope that's ok.

**Comment by josteink** [comment]
I've done some preliminary testing, and as far as I can tell... The `tide-refactor` command does not really work for the supplied sample at all, if in a TypeScript-file.

To make it work, I need to create a **Javascript** file and enable `tide` for my `js-mode` hook too. And to find out that, I needed to dig in various Github issues in the typescript repo.

Is that how it's supposed to work? Or are there refactorings which should be supported in TypeScript too? Right now it's not really very obvious, bordering on undiscoverable.

As such I think we should aim to do better. Would it be possible to add a warning that some refactorings are only available for Javascript-files when tsserver returns that no refactorings are available?

**Comment by ananthakumaran** [comment]
There is only one refactoring available for now and that is only supported for js files.

> As such I think we should aim to do better. Would it be possible to add a warning that some refactorings are only available for Javascript-files when tsserver returns that no refactorings are available?

Well I am ok with adding more info instead of just showing `No refactorings available`, but the caveat is, tsserver could add more refactoring in the future or some plugins could provide extra refactoring options. We can't say for sure.

**Comment by josteink** [comment]
> Well I am ok with adding more info instead of just showing No refactorings available, but the caveat is, tsserver could add more refactoring in the future or some plugins could provide extra refactoring options. We can't say for sure.

How about we display `No refactorings available (A javascript-file may be required)`if we detect that the active major-mode is not `typescript-mode`?

**Comment by josteink** [comment]
So should I just go ahead and make those changes myself?

**Comment by ananthakumaran** [comment]
done

**Comment by josteink** [comment]
LGTM. Merge at will.

**Pull request merged**
