### PR TITLE
improve import autocomplete

### LINKED ISSUE #226: Lost company-files triggering
I've just updated tide and I've lost `company-files` autocompletion.

That is, I was able to type

`import { Example } from "./`

and a popup with the list of files in the current directory would get displayed (as it happens in js-mode and many others).

Can I get this behaviour back again somehow? I've tried customizing `company-backends` but it just didn't work.

Thanks,
Mariano.

### PR DESCRIPTION
**Pull request by ananthakumaran**
fixes #226 

@it6 @mbenedettini can you guys test this branch and see if it improves the situation.

### CODE REVIEW

**Comment by it6** [comment]
works as expected !! 

I noticed a minor thing, for the first time in any file I noticed a delay(only first time), see below.

import

**Comment by ananthakumaran** [comment]
thanks, I guess it's likely tsserver is taking time to index the files for the first time?(could be confirmed by looking at the latency in the logs) tide doesn't do anything different. I guess tide can't do anything here.

**Comment by it6** [comment]
yeah It must be `tsserver`, this is good enough thanks for your help.

**Comment by mbenedettini** [comment]
Working fine here too. Thanks a lot, @ananthakumaran !

**Pull request merged**
