### PR TITLE
Support tsconfig extends tsconfig.json in node_modules

### PR DESCRIPTION
**Pull request by bolasblack**

### CODE REVIEW

**Comment by lddubeau** [comment]
Thanks for the PR. Generally, it is helpful to describe what a PR does. Is this PR meant to fix #317?

**Comment by bolasblack** [comment]
@lddubeau Sorry, I am not very good at expressing.

`extends` in `tsconfig.json` support resolve other `tsconfig.json` from `node_modules`, for example:

```json
{
  "extends": "@sindresorhus/tsconfig",
  // or
  "extends": "@sindresorhus/tsconfig/tsconfig",
  // or
  "extends": "@sindresorhus/tsconfig/tsconfig.json",
}
```

**Comment by ananthakumaran** [comment]
Thanks for the PR, but another PR https://github.com/ananthakumaran/tide/pull/321 which solves the issue has been merged. We decided to offload the work to tsc as the logic has become complicated.

**Comment by bolasblack** [comment]
That’s cool! Thanks for your work!

**Pull request closed without merging**
