### PR TITLE
type and lint errors in web-mode

### PR DESCRIPTION
**Pull request by yatesco**
https://github.com/ananthakumaran/tide/issues/159

### CODE REVIEW

**Comment by ananthakumaran** [comment]
I guess the changes are too verbose and the real issue is with flycheck/tslint-checker configuration. Probably it would best to add the config under the TSX and JSX section and may be explain or point to how chaining and checkers work in flycheck.

**Comment by josteink** [comment]
I don't mind a verbose section as long as it gives a working config. 

If you think it's too verbose to be on the readme, would it perhaps be better to add functions like tide-configure-tslint and tide-configure-web-mode and reference those in the readme?

**Comment by ananthakumaran** [comment]
This just repeats the same config already mentioned in the readme with some minor additions
```elisp
(flycheck-add-mode 'typescript-tslint 'web-mode)
```
Speaking strictly, the issue has nothing to do with tide. But as tide seems to be the starting point of config for many users, we could add it in the readme with a note. 

> would it perhaps be better to add functions like tide-configure-tslint and tide-configure-web-mode and reference those in the readme?

as I mentioned above, this is not tide issue and as such we shouldn't try to fix it in tide

**Comment by yatesco** [comment]
Hi all - comments appreciated. To be blunt, I am dancing around in the dark here, and I imagine I might not be the only one. For example, spacemacs exhibits exactly the same behaviour.

I get completely that this is not `tide`'s insufficiency, rather it is a lack of knowledge around `flycheck`.

Would it be sufficient to reduce this to a note:

> To get both `tide` and `tslint` errors (as seen in `typescript-mode`) simply add ```(flycheck-add-mode 'typescript-tslint 'web-mode)``` to your config?

What do you think?

**Comment by josteink** [comment]
Sounds good to me :)

**Comment by ananthakumaran** [comment]
Closing this. Updated the readme with the details.

**Pull request closed without merging**
