### PR TITLE
ignore empty response incase of eldoc

### LINKED ISSUE #176: ElDoc shows "No content available" in certain places
In certain places, ElDoc shows the message "No content available" instead of showing a function signature. I would expect it to instead show no message at all (because showing this message can obscure other, more useful messages).

I've created [an example repository](https://github.com/raxod502/tide-issue-176) demonstrating the issue. (But you can probably reproduce it just by pasting the code below into your TypeScript project.) Steps to reproduce:

```
$ git clone https://github.com/raxod502/tide-issue-176.git
$ cd tide-issue-176
$ yarn
$ emacs -Q
M-: (require 'tide)
C-x C-f index.ts
M-x tide-setup
M-x eldoc-mode
```

The message shows when point is at the `|`:

```
const foo = [
  function bar() { },|
]
```

The message originally comes from tsserver. Perhaps it should be blacklisted.

### PR DESCRIPTION
**Pull request by ananthakumaran**
fixes #176

### CODE REVIEW

**Comment by ananthakumaran** [comment]
@raxod502 could you try this branch

**Comment by raxod502** [comment]
Unfortunately, this still seems to show the message. If it works on your end then I can try to figure out why.

**Comment by ananthakumaran** [comment]
sorry, I was only testing `quickinfo` command, but your example triggers `signatureHelp`. Now added for both of them. Can you test again?

**Comment by raxod502** [comment]
Works great, thanks for the fix.

**Pull request merged**
