### PR TITLE
add tide-hl-identifier-mode

### PR DESCRIPTION
**Pull request by dominikh**
Add a minor mode for automatically highlighting occurences of an ID.

tide-hl-mode mkv

### CODE REVIEW

**Comment by dominikh** [comment]
Is there a way to limit the tide-command:references query to references in the current file? For types like Event, the current implementation of this PR is too slow, because of all the references in other files and modules.

**Comment by ananthakumaran** [comment]
Sorry for being late. Don't get much free time nowadays.

* Is this code based on any minor-mode? 

* `references` might be a wrong command to use. There is another command named [`documentHighlights`](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L366) which might be suitable.

``` lisp
(defun tide-command:documentHighlights (cb)
  (tide-send-command
   "documentHighlights"
   `(:file ,buffer-file-name :line ,(tide-line-number-at-pos) :offset ,(tide-current-offset) :filesToSearch (,buffer-file-name))
   cb))
```

Don't use the sync version, because it will block emacs till tsserver responds. If we use the async version, we don't have to worry much about the latencies.

**Comment by dominikh** [comment]
> Is this code based on any minor-mode?

I have written similar code for go-guru, to highlight identifiers in Go code. I have the copyright to that code.  The same code does not exist as a generic minor mode, however.

> Don't use the sync version, because it will block emacs till tsserver responds. If we use the async version, we don't have to worry much about the latencies.

The main reason I went with the sync version is that it is much simpler to implement, as we will not have to worry about the user having moved point somewhere else before the result comes in, nor about cancelling outstanding requests when the user moves point. In go-guru, that worked fine because of millisecond response times.

Also, while using the async version would solve the hangs, it would still require fast response times to have a good user experience. Sometimes having to wait a second for a highlight would feel very inconsistent.

> references might be a wrong command to use. There is another command named documentHighlights which might be suitable

I have no experience with tsserver and am having a hard time finding documentation on its API. Where can I look up what exactly that function does?

**Comment by ananthakumaran** [comment]
> I have written similar code for go-guru, to highlight identifiers in Go code. I have the copyright to that code. The same code does not exist as a generic minor mode, however.

sounds great.

> Don't use the sync version, because it will block emacs till tsserver responds. If we use the async version, we don't have to worry much about the latencies.
The main reason I went with the sync version is that it is much simpler to implement, as we will not have to worry about the user having moved point somewhere else before the result comes in, nor about cancelling outstanding requests when the user moves point. In go-guru, that worked fine because of millisecond response times.

> Also, while using the async version would solve the hangs, it would still require fast response times to have a good user experience. Sometimes having to wait a second for a highlight would feel very inconsistent.

Agree, async version might be hard to implement than sync. But it also makes editing experience much smoother. Let's not worry about canceling outstanding requests. We can simply not do anything in the callback if the user has moved off the identifier. tsserver usually response in milliseconds and because we limit the scope of the search to single file, I hope it won't take too long to respond

> I have no experience with tsserver and am having a hard time finding documentation on its API. Where can I look up what exactly that function does?

best bet is to look the source code. [https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts](protocol.ts) contains the interface (request and response format). [session.ts](https://github.com/Microsoft/TypeScript/blob/master/src/server/session.ts#L1571) contains the implementation.

**Comment by dominikh** [comment]
Would you be fine with merging the sync version first, and changing it to an async version in a separate PR? It'd make the change simpler to review. Though I still believe that an async version isn't really necessary. The sync version with millisecond response times has no noticeable delay in Emacs (we've used that in go-guru for months).

I'll give documentHighlights a go and update the PR accordingly.

**Comment by dominikh** [comment]
@ananthakumaran I've pushed a new version of the PR, now using documentHighlights – which works like a charm. It's still using the sync code for now, but it's blazing fast, only throttled by the configurable delay (which defaults to 0.1s)

**Comment by ananthakumaran** [comment]
I will do a proper review soon. Agree, we can convert to async later.

**Pull request merged**
