### PR TITLE
add support for jsdoc tags

### LINKED ISSUE #180: Adding JSDoc tags to documentation window
Currently, documentation using jsdoc tags doesn't show up in the documentation window. Are there any plans to add this? Should be a pretty simple fix, just reading the tags key in the body of the response.

### PR DESCRIPTION
**Pull request by ananthakumaran**
fixes #180

### CODE REVIEW

**Comment by ananthakumaran** [comment]
@sw9 could you test this branch?

**Comment by sw9** [comment]
On first look, it seems that it's only displaying the first tag. Gonna dig down more into the changes.

**Comment by ananthakumaran** [comment]
@sw9 have you got a chance to figure out the issue?
I tried multiple tags, It seems to work ok. tsserver by default ignores some tags like `@param` and `@returns`, I guess it's not added because the information is already present in the signature.
```js
/**
 * @file This is my cool script.
 * @copyright Michael Mathews 2011
 *
 *
 * @example
 * // returns 2
 * globalNS.method1(5, 10);
 * @example
 * // returns 3
 * globalNS.method(5, 15);
 * @returns {Number} Returns the value of x for the equation.
 */
let method1 = function (a, b) {
    return b / a;
};
```


```
let method1: (a: any, b: any) => number

@file This is my cool script.
@copyright Michael Mathews 2011
@example
// returns 2
globalNS.method1(5, 10);
@example
// returns 3
globalNS.method(5, 15);
```

**Comment by sw9** [comment]
Ah my bad, I didn't know that tsserver hides @param and @returns. Everything looks good for me.

**Comment by josteink** [comment]
Awesome. Good job you two :)

**Pull request merged**
