### PR TITLE
trigger rename command after refactor

### PR DESCRIPTION
**Pull request by ananthakumaran**
see https://github.com/Microsoft/TypeScript/pull/18351 for details. This is backward compatible if renameLocation is not present it won't do anything. To test it locally, you need to use `release-2.5` branch of `TypeScript`

### CODE REVIEW

**Comment by josteink** [comment]
I haven't tested it yet, but looking at the code, and the TypeScript-issue that all seems to make sense to me. Looks like a good improvement.

I'll check it in more detail tomorrow.

**Comment by ananthakumaran** [comment]
no need to hurry, take your time.

**Comment by josteink** [comment]
Tested and works. Commit away!

One comment only, and that's really orthogonal to this PR...

The more I use `tide-refactor`, the more I feel it's a stepping-stone I'd rather not use.

In Visual Studio and other editors, I have direct keys for specific refactorings. Some examples: `Ctrl-R Ctrl-R` for symbol-rename, `Ctrl-R Ctrl-M` for method-extraction, etc.

I very often know what I want, and I'd like to just get *right to it* without asking my editor if it's actually an option, because I can tell up front it should be.

Should we add some extra `tide-` commands to apply known refactorings directly without having to use `tide-refactor` as a stepping-stone?

**Comment by ananthakumaran** [comment]
> Should we add some extra tide- commands to apply known refactorings directly without having to use tide-refactor as a stepping-stone?

Yes, we could. It still going to ask about which scope you want to extract the method etc, but in many cases, the operation could be carried away without confirmation.

**Pull request merged**
