### PR TITLE
enable auto import suggestion by default

### LINKED ISSUE #220: Autocomplete can't find names from other files
And it affects also auto-impor feature.
Probably it's because of argument "includeExternalModuleExports", recently added to "completions" command in tsserver.

```
    /**
     * Arguments for completions messages.
     */
    interface CompletionsRequestArgs extends FileLocationRequestArgs {
        /**
         * Optional prefix to apply to possible completions.
         */
        prefix?: string;
        /**
         * If enabled, TypeScript will search through all external modules' exports and add them to the completions list.
         * This affects lone identifier completions but not completions on the right hand side of `obj.`.
         */
        includeExternalModuleExports: boolean;
}
```

### PR DESCRIPTION
**Pull request by ananthakumaran**
fixes #220

### CODE REVIEW

**Comment by josteink** [comment]
LGTM. I like the new auto documentation generator :)

**Comment by domachine** [comment]
Is there anything I can do to help to get this out as a release to MELPA?

**Comment by josteink** [comment]
Do you mean MELPA *stable*? This should have been in "regular MELPA" the day after it was merged.

**Comment by domachine** [comment]
Ah, okay my fault, I'm already on the latest version, sorry. Unfortunately I still have no auto-import suggestions :-( but I think then it's a configuration problem on my side.

**Comment by josteink** [comment]
It's probably tied to the version of TypeScript and tsserver your project uses. Try upgrading your projects Typescript-package to latest and see if that helps.

**Comment by domachine** [comment]
That is so true! Thank you very, very much!

**Pull request merged**
