### PR TITLE
Update tsx-tide checker modes

### PR DESCRIPTION
**Pull request by phuhl**
Fixes https://github.com/ananthakumaran/tide/issues/463

### CODE REVIEW

**Comment by phuhl** [comment]
It works. I have that feeling that it does less then before, though. Not sure how that can be.

**Comment by ananthakumaran** [comment]
You can run `M-x company-diag` to check which backends are used.

**Comment by phuhl** [comment]
Seems to be the wrong one?

```
Emacs 29.0.90 (x86_64-pc-linux-gnu) of 2023-04-26 on ...
Company 0.9.13

company-backends: (company-tide company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-dabbrev
Major mode: tsx-ts-mode
Prefix: ""

```

**Comment by phuhl** [comment]
No worries. Seems to work with the modes added in tide-supported-modes. Added a commit for it.

**Comment by cprussin** [comment]
hey @ananthakumaran , any chance I can request that you cut a release to include this?  I notice it's been a while since a release has been cut anyways.  Thanks a bunch!

**Comment by ananthakumaran** [comment]
@cprussin done

**Pull request merged**
